Readd mapController#geometryTypeValue
removed in 9fc00c4750279512be28f683e79583cc0b04da58, I guess it was an accident.

Fixes this error when switch to add mode:
> Error invoking action "click->map#toggleMode"
> Error: draw_undefined is not valid